services:
  app:
    image: laravel/app:1.0
    build: ./app
    container_name: 'app'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini
      - ../app:/var/www/html
    depends_on:
      - db

  db:
    image: laravel/postgres:1.0
    build: ./db
    container_name: 'db'
    ports:
      - '5432:5432'
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

  web:
    image: nginx:1.19
    container_name: 'web'
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html

volumes: 
  data: